name: Install OpenJPEG

on:
  workflow_call:

jobs:
  install_openjpeg:
    runs-on: macos-latest
    steps:
      # macOS setup
      - name: Install Homebrew on macOS
        uses: melusina-org/setup-macports@v1
      
      - name: Install OpenJPEG on macOS
        run: |
          port install openjpeg
