name: Install OpenJPEG

on:
  workflow_call:

jobs:
  install_openjpeg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check OS
        id: check-os
        run: echo "Running on ${{ matrix.os }}"

      # macOS setup
      - name: Install Homebrew on macOS
        if: matrix.os == 'macos-latest'
        uses: melusina-org/setup-macports@v1
      
      - name: Install OpenJPEG on macOS
        if: matrix.os == 'macos-latest'
        run: |
          port install openjpeg

      
      - name: Install cygwin on Windows with openjpeg
        if: matrix.os == 'windows-latest'
        uses: cygwin/cygwin-install-action@master
        with:
          packages: openjpeg
